INSERT INTO series (title, author_id, subgenre_id) VALUES ("Kingkiller", 1, 2);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Pendergast", 2, 1);
INSERT INTO subgenres (name) VALUES ("urban fantasy");
INSERT INTO subgenres (name) VALUES ("legal thriller");
INSERT INTO authors (name) VALUES ("Patrick Rothfuss");
INSERT INTO authors (name) VALUES ("Douglas Preston");
INSERT INTO books (title, year, series_id) VALUES ("The Name of the Wind", 2007, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Wise Man's Fear", 2011, 1);
INSERT INTO books (title, year, series_id) VALUES ("Doors of Stone", 3000, 1);
INSERT INTO books (title, year, series_id) VALUES ("Relic", 1995, 2);
INSERT INTO books (title, year, series_id) VALUES ("Reliquary", 1997, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Cabinet of Curiosities", 2002, 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Kvothe", "Damn Ambrose twelve ways", "human", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Denna", "I suck", "human", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Bast", "Whoops", "fae", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Auri", "Everything has a proper name", "human", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Aloysius Pendergast", "Is that so?", "human", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Vincent D'Agosta", "Pendergast!", "human", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Constance Greene", "That will be all", "human", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Proctor", "As you wish", "human", 1);
INSERT INTO character_books (character_id, book_id) VALUES(1, 1);
INSERT INTO character_books (character_id, book_id) VALUES(1, 2);
INSERT INTO character_books (character_id, book_id) VALUES(1, 3);
INSERT INTO character_books (character_id, book_id) VALUES(2, 1);
INSERT INTO character_books (character_id, book_id) VALUES(2, 2);
INSERT INTO character_books (character_id, book_id) VALUES(2, 3);
INSERT INTO character_books (character_id, book_id) VALUES(3, 1);
INSERT INTO character_books (character_id, book_id) VALUES(4, 1);
INSERT INTO character_books (character_id, book_id) VALUES(5, 4);
INSERT INTO character_books (character_id, book_id) VALUES(5, 5);
INSERT INTO character_books (character_id, book_id) VALUES(5, 6);
INSERT INTO character_books (character_id, book_id) VALUES(6, 4);
INSERT INTO character_books (character_id, book_id) VALUES(6, 5);
INSERT INTO character_books (character_id, book_id) VALUES(6, 6);
INSERT INTO character_books (character_id, book_id) VALUES(7, 4);
INSERT INTO character_books (character_id, book_id) VALUES(8, 5);